/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs129l.pkgfinal.project;

import DataStructs.Lot;
import PresentationPanels.LotSearchPanel;
import PresentationPanels.RowPresentation;
import Rows_and_UIs.LotRow;
import SearchFunctions.LotSearchBar;
import java.awt.FlowLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author nicht
 */
public class TestyBoi extends javax.swing.JFrame {

    /**
     * Creates new form TestyBoi
     */
    public TestyBoi() {
        initComponents();/*
        this.setLayout(new FlowLayout());
        this.setSize(1080, 720);
        this.setVisible(true);
        RowPresentation test1 = new RowPresentation();
        SQLConn c = new SQLConn();
        //this.add(new LotSearchPanel(c));
        this.add(new LotSearchBar(test1,c ));
        this.add(test1);*/
        JPanel testy = new JPanel();
        testy.setSize(1080, 720);
        testy.setVisible(true);
        JPanel fucker1 = new JPanel();
        fucker1.setSize(1000,700);
        fucker1.setVisible(true);
        testy.setLayout(new BoxLayout(testy, BoxLayout.Y_AXIS));
        fucker1.setLayout(new BoxLayout(fucker1, BoxLayout.Y_AXIS));
        Lot temp = new Lot("A,B,C,D,1,2");
        fucker1.add(new LotRow(temp));
        fucker1.add(new LotRow(temp));
        fucker1.add(new LotRow(temp));
        fucker1.add(new LotRow(temp));
        testy.add(fucker1);
        testy.add(fucker1);
        testy.add(new LotRow(temp));
        this.add(testy);
        
        System.out.println("RULE BRITANNIA: "+testy.getLayout().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestyBoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestyBoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestyBoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestyBoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestyBoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
