/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs129l.pkgfinal.project.SearchFunctions;
<<<<<<< HEAD:CS129L Final Project/CS129L Final Project/src/cs129l/pkgfinal/project/SearchFunctions/LotSearchBar.java
import cs129l.pkgfinal.project.Lot;
import java.util.ArrayList;

public class LotSearchBar extends SearchPrototype {
    
    public LotSearchBar() {
=======

/**
 *
 * @author nicht
 */
public class LotSearchBlock extends javax.swing.JPanel {

    /**
     * Creates new form LotSearchBlock
     */
    public LotSearchBlock() {
>>>>>>> 7f5a7fe3f0df41cfe8c3da6f73e2ca953f0b78ff:CS129L Final Project/CS129L Final Project/src/cs129l/pkgfinal/project/SearchFunctions/LotSearchBlock.java
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD:CS129L Final Project/CS129L Final Project/src/cs129l/pkgfinal/project/SearchFunctions/LotSearchBar.java
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String query ="SELECT * FROM LOT WHERE";
        query += generateSubCond(query," LOT_CODE LIKE",jTextField1);
        query += generateSubCond(query," NAME LIKE",jTextField2);
        query += generateSubCond(query," SQM",jTextField3,jTextField4);
        query += generateSubCond(query," SQM_COST",jTextField5,jTextField6);
        query += generateSubCond(query," TOTAL_COST",jTextField7,jTextField8);
        if("AND".equals(query.substring(query.length()-3))){query=query.substring(0, query.length()-3);}
        ArrayList<Lot> lots = c.LotSearch(query);
        Panel.BuildRow(lots);
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        String query ="SELECT * FROM LOT WHERE";
        query += generateSubCond(query," LOT_CODE LIKE",jTextField1);
        query += generateSubCond(query," NAME LIKE",jTextField2);
        query += generateSubCond(query," SQM",jTextField3,jTextField4);
        query += generateSubCond(query," SQM_COST",jTextField5,jTextField6);
        query += generateSubCond(query," TOTAL_COST",jTextField7,jTextField8);
        if("AND".equals(query.substring(query.length()-3))){query=query.substring(0, query.length()-3);}
        System.out.println(query);
        ArrayList<Lot> lots = c.LotSearch(query);
        Panel.Clear();
    }//GEN-LAST:event_SearchButton1ActionPerformed

=======
>>>>>>> 7f5a7fe3f0df41cfe8c3da6f73e2ca953f0b78ff:CS129L Final Project/CS129L Final Project/src/cs129l/pkgfinal/project/SearchFunctions/LotSearchBlock.java

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
